### ISSUE TITLE
Alert rules not resilient against leader failure

### ISSUE THREAD

**Issue by mmanciop** [canonical/prometheus-k8s-operator#104] opened 2021-08-20 07:53 UTC
If the leader unit of the charm with built-in alert rules experiences failure, alert rules are not reliably sent to Prometheus. We should consider updating alert rules in the relation data when the leader unit of the charm with built-in alert rules is elected.

**Comment by balbirthomas** [comment] 2021-08-24 08:14
You mean every time a new leader is elected for the `MetricsEndpointProvider` charm, if required alert rules should be updated.

**Comment by mmanciop** [comment] 2021-08-24 08:20
I am hazy on whether a `juju refresh` will always cause a new leader to be elected, especially when the Juju application has just one unit. So we might need both the `on.upgrade_charm` and `on.leader_elected` hooks to be registered and acted upon only by the new leader.

**Comment by balbirthomas** [comment] 2021-11-22 13:51
I tried to reproduce this issue as follows

1. Deploy prometheus-k8s and prometheus-tester adding a relation between the two
2. The used kubectl to delete the leader pod of prometheus (since `juju remove-unit` is not supported on k8s)

However Juju created a new pod without reassigning the leader to the other (non deleted) pod. There is a juju hook tool called `leader-set` but AFAIK this does not change the leader itself only created "leader setting" key value pairs. Hence I am not sure if there is controlled way to reproduce this issue.

It is of course trivial to add a leader elected event handler binding it to the config changed handler or upgrade handler. However since all relation data is stored as application relation data the newly elected leader (of `MetricsEndpointProvider`) does not have to do anything to assert leadership, since the application data should still persist.

**Comment by balbirthomas** [comment] 2021-11-29 13:07
I tried the following. 

1. Deployed 10 units of Prometheus (`juju deploy prometheus-k8s -n 10 --channel=edge`). Unit 3 was the leader.
2. Deployed [prometheus-tester](https://github.com/balbirthomas/prometheus-tester) and added a relation with Prometheus.
3. Checked that all Prometheus were scrapping the prometheus-tester target and had associated alert rules.
4. Scaled down Prometheus application to 1 (`juju scale-application prometheus-k8s 1`). Unit 0 became the leader.
5. Checked that Unit 0 was still being scrapped by Prometheus and still had the associated alert rules.

**Comment by mmanciop** [comment] 2021-11-29 13:54
And I assume your test worked @balbirthomas ? :-)

The failure scenario I had in mind actually is the following:

1. Deploy a new charm, which fails to elect a leader
2. Scrape jobs and alert rules are never sent to Prometheus because there is no leader that can write the app data bag, and Prometheus does not know anything about the missing jobs and alerts

IMO, we might want to actually create something on Prometheus side to ensure that scrape jobs and, optionally, alert rules, are sent over the relation data. Fundamentally, the only provider of `prometheus_scrape` relations that are entitles not to have scrape jobs are `MetricsEndpointAggregators`.

**Comment by simskij** [comment] 2021-11-29 14:00
Agreed. So what we're saying is that if someone providing `prometheus_scrape` lacks a scrape job, we should act on that. And if that happens, we should likely also reload alert rules as well as they will likely be borked as well?

**Comment by mmanciop** [comment] 2021-11-29 14:04
The lma-rules charm, as well as the LMA Proxy charm, imonare exceptions because they are, to the best of my knowledge, implemented using the MetricsEndpointAggregator.

For any charm implementing MetricsEndpointProvider, there must be at least the default scrape job, and if it is not there, there is something fishy going on :-)

**Comment by balbirthomas** [comment] 2021-11-29 14:04
@mmanciop Actually the above 5 steps I tried did not reproduce the issue. It is trivial (one line) to bind the leader elected event to `_configure()` method of the Prometheus charm. I am quite confident if there is any issue here then this one line change will fix the issue. I am happy to do this if that is OK with you. However I am not sure how I can reproduce "Depoly a new charm that fails to elect a leader". 

@simskij If I understand you and @mmanciop correctly then what needs to be done seems to be to detect if a `prometheus_scrape` relation exists without any scrape jobs and set `BlockedStatus` . Note that even if any charm does not submit any scrape jobs Prometheus charm will create a default scrape job for that charm and try to scrape it.

**Comment by mmanciop** [comment] 2021-11-29 14:06
> @mmanciop Actually the above 5 steps I tried did not reproduce the issue. It is trivial (one line) to bind the leader elected event to _configure() method of the Prometheus charm. I am quite confident if there is any issue here then this one line change will fix the issue. I am happy to do this if that is OK with you. However I am not sure how I can reproduce "Depoly a new charm that fails to elect a leader".

Bugged charm :-)

**Comment by simskij** [comment] 2021-11-29 14:30
> [...] will create a default scrape job for that charm and try to scrape it.

@mmanciop @balbirthomas Is this what we desire to happen? If so, should we add some kind of label that tells that it's a generated fallback in case this occurs. That would allow us to later check whether we're using a supplied scrape target or a self-generated one, and if the latter - rerun the fetch logic.

**Comment by balbirthomas** [comment] 2021-11-29 14:39
@simskij A default scrape job is as per requirements. If `MetricsEndpointProvider` constructor is not provided a scrape job when being instantiated, the scrape job is set to `[{"metrics_path": "/metrics"}]`. As a result the Prometheus charm will scrape each unit of the "Metrics Provider Charm" at the "/metrics" path. At present this is no label or log that distinguishes this case from those where an explicit scrape job specification has been set.

**Comment by dstathis** [comment] 2022-05-11 21:14
I don't think it makes sense to block if no scrape job is provided. That will always be the case if a hook fires before the provider adds its relation data.

**Comment by dstathis** [comment] 2022-05-11 22:00
I think I see what the issue is here. If the *provider* has no leader when relation-joined fires, then no unit will write alert rules to the relation.

**Comment by balbirthomas** [comment] 2022-05-12 10:12
> I think I see what the issue is here. If the _provider_ has no leader when relation-joined fires, then no unit will write alert rules to the relation.

A test may help to pin point the issue, if it exists. But be aware that unit test can mislead. The were ambiguities in the ordering of leadership election and relation events, for example see [operator issue 697](https://github.com/canonical/operator/issues/697).

**Closed** 2022-07-21 14:42 UTC
Labels: Priority: Medium, Status: Testing Needed, Type: Bug
