### ISSUE TITLE
Blocked status due to broken config not correctly cleaned up when issue resolved?

### ISSUE THREAD

**Issue by mmanciop** [canonical/prometheus-k8s-operator#181] opened 2021-12-07 10:56 UTC
I related with Prometheus a local version of a charm with a mistake in the promql of an alert rule. Correctly Prometheus when into Blocked state. But when I refreshed my local charm after correcting the error, Prometheus remained in Blocked state, although the configuration now is clean according to `promtool`, see below:

```
michele@boombox:~/git/spring-music$ microk8s.kubectl exec -n lma prometheus-0 -c prometheus -- promtool check config /etc/prometheus/prometheus.yml
Checking /etc/prometheus/prometheus.yml
  SUCCESS: 1 rule files found

Checking /etc/prometheus/rules/juju_spring_29359a6e-50bb-412d-857c-1c4b4422ba32_spring-music_alerts.rules
  SUCCESS: 3 rules found

michele@boombox:~/git/spring-music$ juju status
Model  Controller   Cloud/Region        Version  SLA          Timestamp
lma    development  microk8s/localhost  2.9.21   unsupported  11:53:28+01:00

App           Version  Status   Scale  Charm             Store     Channel  Rev  OS          Address         Message
alertmanager           active       1  alertmanager-k8s  charmhub  edge       7  kubernetes  10.152.183.187  
grafana                waiting    0/1  grafana-k8s       charmhub  edge      14  kubernetes  10.152.183.48   installing agent
loki                   active       1  loki-k8s          local                5  kubernetes  10.152.183.7    
prometheus             waiting      1  prometheus-k8s    charmhub  edge      12  kubernetes  10.152.183.131  installing agent

Unit             Workload  Agent  Address       Ports  Message
alertmanager/0*  active    idle   10.1.151.92          
grafana/0        unknown   lost   10.1.151.101         agent lost, see 'juju show-status-log grafana/0'
loki/0*          active    idle   10.1.151.102         
prometheus/0*    blocked   idle   10.1.151.97          Failed to load Prometheus config

Offer                         Application   Charm             Rev  Connected  Endpoint           Interface          Role
alertmanager-karma-dashboard  alertmanager  alertmanager-k8s  7    0/0        karma-dashboard    karma_dashboard    provider
grafana-dashboards            grafana       grafana-k8s       14   1/1        grafana-dashboard  grafana_dashboard  requirer
loki-logging                  loki          loki-k8s          5    1/1        logging            loki_push_api      provider
prometheus-scrape             prometheus    prometheus-k8s    12   1/1        metrics-endpoint   prometheus_scrape  requirer
```

**Comment by balbirthomas** [comment] 2021-12-07 10:59
Interesting. Will investigate. Thanks for reporting.

**Comment by balbirthomas** [comment] 2021-12-08 15:37
I did try to reproduce this bug by 

- introducing a invalid alert rule into prometheus-tester and adding a relation with prometheus-k8s
- this did lead to blocked status
- removing the invalid rule, rebuilding, redeploying and refreshing the prometheus-tester charm
This failed to reproduce the bug since the Prometheus charm did successfully exit from the blocked status.

In view of the above I am closing this bug report. Thank you for reporting. Feel free to reopen if this happens again or the bug is reproducible with different conditions of reproducibility.

**Closed by balbirthomas** 2021-12-08 15:37 UTC
Labels: bug
