### ISSUE TITLE
prometheus fails to reload the configuration on deploy

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/prometheus-k8s-operator#525] opened 2023-09-12 12:05 UTC
### Bug Description

prometheus sets blocked status on deploy. It gets cleared after the first update-status.

### To Reproduce

`juju deploy cos-lite --channel=edge --trust`

### Environment

```
                         juju info v0.1                         
┌──────────────┬───────────────────────────────────────────────┐
│ jhack        │ 0.3.19.1.2                                    │
│ python       │ 3.8.18 (/home/pietro/.venvs/jhack/bin/python) │
│ juju-* snaps │  juju │ 3.2.2 - 23846 (3.2/stable)            │
│ microk8s     │ MicroK8s v1.27.5 revision 5892                │
│ lxd          │ 5.17                                          │
│ multipass    │ 1.12.2                                        │
│ multipassd   │ 1.12.2                                        │
│ os           │ Ubuntu 22.04.3 LTS                            │
│ kernel       │ Linux 6.2.0-32-generic x86_64                 │
└──────────────┴───────────────────────────────────────────────┘
```

### Relevant log output

```shell
unit-prometheus-0: 13:25:59 INFO unit.prometheus/0.juju-log certificates:29: Prometheus (re)started
unit-prometheus-0: 13:25:59 ERROR unit.prometheus/0.juju-log certificates:29: Prometheus failed to reload the configuration
```

**Comment by PietroPasotti** [comment] 2023-09-12 13:34
probably a timing issue; validate-configuration shows everything is fine.

**Comment by sed-i** [comment] 2023-09-20 14:26
Could also be a TLS issue -- https before the cert is there?

**Comment by sed-i** [comment] 2024-07-26 13:49
Can't reproduce. Closing for now.
Feel free to reopen with more details.

**Closed by sed-i** 2024-07-26 13:49 UTC
Labels: Status: Triage, Type: Bug
