### ISSUE TITLE
MetricsEndpointConsumer does not support `upgrade_charm`

### ISSUE THREAD

**Issue by mmanciop** [canonical/prometheus-k8s-operator#188] opened 2021-12-15 12:20 UTC
The `MetricsEndpointConsumer` does not have support for the `upgrade_charm` event, which leads to Prometheus not noticing the scrape job and alert rules changes when developing in local and updating Prometheus (e.g., for bug fixes in Prometheus operator itself).

I am unsure whether the bug would trigger in production, e.g., when the release changes the Prometheus container image and churns the pods. I _think_ in that case we will get `relation_joined` and it would work, but it is not a scenario we test in integration tests atm.

**Comment by simskij** [comment] 2022-02-16 16:18
Test if there **is** still a bug, if there is a bug; we need a test that verifies it and then fix the bug.

**Comment by balbirthomas** [comment] 2022-02-28 16:12
I am unable to reproduce this bug hence closing it. Also it is the `MetricsEndpointProvider` that updates alert rules on upgrade charm.

**Closed by balbirthomas** 2022-02-28 16:12 UTC
Labels: Type: Bug
